#
# Placeholders used in here:
# <[player]> = The player that died.
#

CONTACT:
  - "<green><[player]> <yellow>hugged a <red>Cactus<yellow>. Not smart."
  - "<green><[player]> <yellow>came into contact with something very prickly."
CRUSHED:
  - "<green><[player]> <yellow>was squashed."
DROWNING:
  - "<green><[player]> <yellow>continued on their journey to the bottom of the <red>Ocean."
  - "<green><[player]> <yellow>didn't bring enough air for their under water journey."
  - "<green><[player]> <yellow>just kept swimming, like Dory said."
  - "<yellow>Gurgle gurgle, blub blub. These were <green><[player]><yellow>'s final words."
  - "<green><[player]> <yellow>forgot they haven't evolved gills yet."
FALL:
  - "<green><[player]> <yellow>answered the call of <red>gravity<yellow>."
  - "<green><[player]> <yellow>forgot to bring a parachute."
  - "<green><[player]> <yellow>did not fly, just fell with style."
  - "<yellow>It's not the fall that kills you, <green><[player]><yellow>. It's the sudden stop at the bottom."
  - "<green><[player]> <yellow>did indeed bumble and took quite a tumble."
  - "<green><[player]> <yellow>broke more than their legs in that jump."
FALLING_BLOCK:
  - "<green><[player]> <yellow>tried to wear an <red>Anvil <yellow>. It was too heavy."
  - "Hey, <green><[player]><yellow>. <red>Anvils <yellow>don't belong on your head."
FIRE:
  - "<green><[player]> <red>burned <yellow>to death."
  - "<yellow>Can you smell what The Rock is cookin', <green><[player]><yellow>? It's you!"
  - "<green><[player]> <yellow>died in a fire."
  - "<green><[player]> <yellow>was cremated."
  - "<green><[player]> <yellow>is quite flammable, tests show."
  - "<green><[player]> <yellow>was incinerated."
FLY_INTO_WALL:
  - "<green><[player]> <yellow>flew into a wall, got turned into a thin streak of goo."
  - "<green><[player]> flew too close to the su.. er, that wall."
HOT_FLOOR:
  - "<green><[player]> <yellow>got nice and toasty on a <red>Magma Block<yellow>."
LAVA:
  - "<green><[player]> <yellow>took a <red>Lava <yellow>bath."
  - "<green><[player]> <yellow>discovered just how hot <red>Lava <yellow>really is."
  - "<yellow>Bathing in <red>Lava <yellow>is not how you get clean, <green><[player]><yellow>."
LIGHTNING:
  - "<green><[player]> <yellow>was given a <red>shocking <yellow>revelation."
  - "<green><[player]> <yellow>has heard of <red>shock humour<yellow>, but this is ridiculous."
  - "<yellow>Zeus was displeased with <green><[player]><yellow>."
  - "<green><[player]> <yellow>now understands what an electrifying experience being outside in a storm can be."
POISON:
  - "<green><[player]> <yellow>was <red>poisoned <yellow>to death."
  - "<yellow>There was no antidote for <green><[player]><yellow>. They died of <red>poisoning<yellow>."
PRIMED_TNT:
  - "<green><[player]> <yellow>blew up with the help of some <red>TNT<yellow>."
  - "<green><[player]> <yellow>stood too lose to <red>TNT<yellow>."
PROJECTILE:
  - "<green><[player]> <yellow>was ventilated by a trap!"
  - "<green><[player]> <yellow>walked into a trap. Didn't walk out."
STARVATION:
  - "<green><[player]> <red>starved <yellow>to death."
  - "<green><[player]> needs to eat a sammich, died of <red>starvation<yellow>."
SUFFOCATION:
  - "<green><[player]> <red>suffocated."
  - "<green><[player]> <yellow>forgot how to breath."
  - "<green><[player]> <yellow>ran out of air."
SUICIDE:
  - "<green><[player]> <yellow>has been slain by <green><[player]><yellow>."
  - "<green><[player]> <yellow>committed sudoku. Er, wait. I meant <red>suicide<yellow>."
VOID:
  - "<green><[player]> <yellow>found the <red>Void<yellow>."
  - "<yellow>You need to avoid the <red>Void<yellow>, <green><[player]><yellow>."
  - "<green><[player]> <yellow>fell into the <red>Void<yellow>!"
  - "<green><[player]> <yellow>discovered that the <red>Void <yellow>really is endless.'"
  - "<green><[player]> <yellow>fell through the bottom of the world. Wow."
  - "<green><[player]> <yellow>embraced eternity."
  - "<green><[player]> <yellow>jumped to infinity and beyond."
  - "<green><[player]> <yellow>fell into the void."
  - "<green><[player]> <yellow>explored the great beyond."
  - "<green><[player]> <yellow>went exploring in the <red>Void<yellow>."
