# 翻译/Translator: Github@CodingEric
#
# 这里使用的占位符：
# <[victim]> = 挂了的玩家。
#

CONTACT:
  - "<green><[victim]><yellow>抱了抱<red>仙人掌<yellow>。不是很聪明的亚子。"
  - "<green><[victim]><yellow>亲了亲某个长刺的玩意儿。"
CRUSHED:
  - "<green><[victim]><yellow>从一个人挤成了一坨人。"
DROWNING:
  - "<green><[victim]><yellow>的尸体正在<red>海底两万里<yellow>。"
  - "<green><[victim]><yellow>因为氧气不够牺牲在了水下长征的开始。"
  - "<green><[victim]><yellow>游进了来生。"
  - "<yellow><green><[victim]><yellow>的遗言是：咕噜咕噜咕噜。"
  - "<green><[victim]><yellow>忘记自己还没进化出鳍。"
FALL:
  - "<green><[victim]><yellow>响应了<red>牛顿<yellow>的召唤。"
  - "<green><[victim]><yellow>忘带降落伞了。"
  - "<green><[victim]><yellow>摔出了英雄本色。"
  - "<yellow>杀死你的不是坠落，<green><[victim]><yellow>。而是地面的鲜花。"
  - "<yellow>善骑者坠于马，善水者溺于水。而善摔者<green><[victim]><yellow>嘛……"
  - "<green><[victim]><yellow>从一个人摔成了一坨人。"
  - "<green><[victim]><yellow>失去同步。"
FALLING_BLOCK:
  - "<green><[victim]><yellow>试图戴上<red>铁砧<yellow>。可惜有点重。"
  - "<yellow><green><[victim]><yellow>同学！<red>铁砧<yellow>不是长在头上的！"
FIRE:
  - "<green><[victim]>被<red>烧<yellow>死了。"
  - "<yellow>猜猜什么煮熟了，<green><[victim]><yellow>？"
  - "<green><[victim]><yellow>在火灾中英勇牺牲。"
  - "<green><[victim]><yellow>火化了。"
  - "<yellow>研究表明，<green><[victim]><yellow>极易燃烧。"
  - "<green><[victim]><yellow>涅槃飞升了。"
FLY_INTO_WALL:
  - "<green><[victim]><yellow>狗急撞墙。"
  - "<yellow>古有飞蛾扑火，今有<green><[victim]><yellow>扑墙。"
HOT_FLOOR:
  - "<green><[victim]><yellow>被<red>熔岩<yellow>烤的嘎嘣脆。"
  - "<green><[victim]><yellow>的脚趾十分熟了。"
LAVA:
  - "<green><[victim]><yellow>洗了个<red>岩浆<yellow>浴。"
  - "<green><[victim]><yellow>明白了<red>岩浆<yellow>有多热。"
  - "<green><[victim]><yellow>，在<red>岩浆<yellow>里打滚不是清洁的好方法。"
LIGHTNING:
  - "<green><[victim]><yellow>在<red>雷雨天气<yellow>渡劫升天。"
  - "<green><[victim]><yellow>遭遇了<red>雷公<yellow>的休克打击。"
  - "<green><[victim]><yellow>触怒了王母娘娘。"
  - "<green><[victim]><yellow>用生命诠释了打雷不要出门的道理。"
POISON:
  - "<green><[victim]><red>中毒<yellow>身亡。"
  - "<yellow>没有解药了，<green><[victim]><yellow>。和其他<red>中毒<yellow>而亡的骸骨永远待在地下吧。"
PRIMED_TNT:
  - "<green><[victim]><yellow>重蹈了<red>万户<yellow>的覆辙。"
  - "<green><[victim]><yellow>引爆<red>炸药<yellow>的时候跑得太慢。"

PROJECTILE:
  - "<green><[victim]><yellow>被陷阱阴了一发。"
  - "<yellow>走进陷阱的是<green><[victim]><yellow>的肉体，走出的是TA的灵魂。"
  - "<green><[victim]><yellow>被陷阱打成了筛子。"
STARVATION:
  - "<green><[victim]><red>饿<yellow>死了"
  - "<yellow>朱门酒肉臭，<green><[victim]><yellow>却<red>没能吃到一片面包<yellow>。"
SUFFOCATION:
  - "<green><[victim]><red>被自己的窒息操作窒息了。"
  - "<green><[victim]><yellow>忘了咋呼吸。"
  - "<green><[victim]><yellow>氧气用完了。"
SUICIDE:
  - "<green><[victim]><yellow>掏出上古神剑，召唤九州之灵，电闪雷鸣，仿佛终末天启。一声尖啸，剑拔出鞘，可惜失手，刎了自己。"
  - "<green><[victim]><yellow>，这个世界虽然不完美，但我们仍然可以疗愈自己。<red>自杀<yellow>干预热线：010-82951332。"
VOID:
  - "<yellow>勇敢的探险家<green><[victim]><yellow>牺牲在<red>万劫虚空<yellow>。"
  - "<yellow>下次得避开<red>虚空<yellow>了，<green><[victim]><yellow>同学。"
  - "<green><[victim]><yellow>牺牲在<red>万劫虚空<yellow>！"
  - "<green><[victim]><yellow>用实践证明了<red>虚空<yellow>真的是空的。"
  - "<yellow>震惊！<green><[victim]><yellow>在基岩之下竟遭遇这种惨剧！"
  - "<green><[victim]><yellow>在世界边缘拥抱虚空的永生。"
  - "<green><[victim]><yellow>跃入无尽虚空。"
  - "<green><[victim]><yellow>牺牲在万劫虚空。"
  - "<green><[victim]><yellow>探索到了世界的边缘。"
  - "<green><[victim]><yellow>到<red>虚空<yellow>一游。"
