name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'RandomDeathMessages.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig README'

- name: Upload Release
  uses: ncipollo/release-action@v1
  with:
    artifacts: "RandomDeathMessages.zip"
    token: ${{ secrets.GITHUB_TOKEN }}